import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Muhammet Coskun | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          justifyContent: "flex-start",
          marginTop: "300px",
          pl: 3,
        }}
      >
        <h1 style={{ fontSize: "50px" }}>
          <strong>Hi, I am Muhammet Coskun!</strong>
        </h1>
      </Box>
      <Box sx={{ pl: 3 }}>
        <p style={{ fontSize: "35px" }}>Front-end web developer.</p>
      </Box>
    </div>
  );
};

export default Home;
