import type { NextPage } from "next";
import Layout from "../src/components/Layout/Layout";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Muhammet Coskun | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ margin: "400px" }}>
        <h1 style={{ fontSize: "64px" }}>
          <strong>Hi, Im Muhammet Coskun!</strong>
        </h1>
        <h2 style={{ fontSize: "32px" }}>Front-end web developer.</h2>
      </div>
    </div>
  );
};

export default Home;
